# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetGiftStoreDetails.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'GetGiftStoreDetails.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19GetGiftStoreDetails.proto\x12\x05proto\",\n\x18\x43SGetGiftStoreDetailsReq\x12\x10\n\x08store_id\x18\x01 \x01(\r\"\x9e\x03\n\x08GiftItem\x12\x14\n\x0c\x63ommodity_id\x18\x01 \x01(\r\x12\x0f\n\x07sort_id\x18\x02 \x01(\r\x12\x0f\n\x07item_id\x18\x03 \x01(\r\x12\x13\n\x0b\x63oins_price\x18\x04 \x01(\r\x12\x12\n\ngems_price\x18\x05 \x01(\r\x12\x10\n\x08tag_type\x18\x06 \x01(\r\x12\x11\n\ttag_value\x18\x07 \x01(\r\x12\x15\n\rtype_override\x18\x08 \x01(\r\x12\x1f\n\x17is_original_type_remain\x18\t \x01(\x08\x12\x14\n\x0cis_exclusive\x18\n \x01(\x08\x12\x11\n\timage_url\x18\x0b \x01(\t\x12!\n\x19is_quick_gift_recommended\x18\x0c \x01(\x08\x12\x12\n\naward_time\x18\r \x01(\r\x12\x18\n\x10\x65xpire_timestamp\x18\x0e \x01(\x03\x12\x14\n\x0c\x64isplay_rare\x18\x0f \x01(\r\x12\x16\n\x0e\x64iscount_price\x18\x10 \x01(\r\x12\x16\n\x0e\x64iscount_start\x18\x11 \x01(\x03\x12\x14\n\x0c\x64iscount_end\x18\x12 \x01(\x03\"\x90\x01\n\x18\x43SGetGiftStoreDetailsRes\x12\x10\n\x08store_id\x18\x01 \x01(\r\x12\x1e\n\x05items\x18\x02 \x03(\x0b\x32\x0f.proto.GiftItem\x12\x1d\n\x15send_gift_times_today\x18\x03 \x01(\r\x12#\n\x1bprime_send_gift_times_today\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetGiftStoreDetails_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETGIFTSTOREDETAILSREQ']._serialized_start=36
  _globals['_CSGETGIFTSTOREDETAILSREQ']._serialized_end=80
  _globals['_GIFTITEM']._serialized_start=83
  _globals['_GIFTITEM']._serialized_end=497
  _globals['_CSGETGIFTSTOREDETAILSRES']._serialized_start=500
  _globals['_CSGETGIFTSTOREDETAILSRES']._serialized_end=644
# @@protoc_insertion_point(module_scope)
