# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SendGift.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'SendGift.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSendGift.proto\x12\x05proto\"\xb2\x01\n\rCSSendGiftReq\x12\x1c\n\x14receiver_account_ids\x18\x01 \x03(\x04\x12\x12\n\nbuddy_type\x18\x02 \x01(\r\x12\x14\n\x0c\x63ommodity_id\x18\x03 \x01(\r\x12\x17\n\x0fmessage_content\x18\x04 \x01(\t\x12\x15\n\rcurrency_type\x18\x05 \x01(\r\x12\x15\n\rcommodity_cnt\x18\x07 \x01(\r\x12\x12\n\nunit_price\x18\x0b \x01(\r\"B\n\rCSSendGiftRes\x12\x12\n\nremove_ids\x18\x01 \x03(\x04\x12\x1d\n\x15send_gift_times_today\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendGift_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSSENDGIFTREQ']._serialized_start=26
  _globals['_CSSENDGIFTREQ']._serialized_end=204
  _globals['_CSSENDGIFTRES']._serialized_start=206
  _globals['_CSSENDGIFTRES']._serialized_end=272
# @@protoc_insertion_point(module_scope)
